# Generated by Django 3.2.8 on 2021-11-02 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Product_id')),
                ('name', models.CharField(max_length=255, verbose_name='폴더 이름')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='폴더 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성된 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='수정된 날짜')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='삭제된 날짜')),
                ('Is_deleted', models.BooleanField(default=False, verbose_name='삭제된 브랜드인지 여부')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name_plural': '폴더',
                'db_table': 'folders',
                'ordering': ['created_at'],
                'managed': True,
            },
        ),
    ]
