# Generated by Django 3.2.8 on 2021-11-02 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addedBrand',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='추가된 브랜드 id')),
                ('name', models.CharField(max_length=255, verbose_name='추가된 브랜드 이름')),
                ('en_name', models.CharField(max_length=255, verbose_name='추가된 브랜드 영어 이름')),
                ('site_url', models.CharField(max_length=255, null=True, verbose_name='추가된 브랜드 사이트 url')),
                ('logo_url', models.CharField(max_length=255, null=True, verbose_name='추가된 브랜드 로고 url')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성된 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='수정된 날짜')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='삭제된 날짜')),
                ('Is_deleted', models.BooleanField(default=False, verbose_name='삭제된 브랜드인지 여부')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name_plural': '유저가 추가한 브랜드',
                'db_table': 'added_brands',
                'ordering': ['created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='브랜드 id')),
                ('name', models.CharField(max_length=255, verbose_name='브랜드 이름')),
                ('en_name', models.CharField(max_length=255, verbose_name='브랜드 영어 이름')),
                ('site_url', models.CharField(max_length=255, null=True, verbose_name='브랜드 url')),
                ('logo_url', models.CharField(max_length=255, null=True, verbose_name='로고 url')),
                ('total_click_count', models.BigIntegerField(default=0, verbose_name='브랜드를 클릭한 횟수')),
                ('like_count', models.BigIntegerField(default=0, verbose_name='브랜드를 좋아요한 횟수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성된 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='수정된 날짜')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='삭제된 날짜')),
                ('Is_deleted', models.BooleanField(default=False, verbose_name='삭제된 브랜드인지 여부')),
            ],
            options={
                'verbose_name_plural': '브랜드',
                'db_table': 'brands',
                'ordering': ['created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='likedBrand',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='브랜드 id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성된 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='수정된 날짜')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='삭제된 날짜')),
                ('Is_deleted', models.BooleanField(default=False, verbose_name='좋아요 취소된 브랜드인지 여부')),
                ('added_brand_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brand.addedbrand')),
                ('brand_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brand.brand')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name_plural': '유저가 담은 브랜드',
                'db_table': 'liked_brands',
                'ordering': ['created_at'],
                'managed': True,
            },
        ),
    ]
