# Generated by Django 3.2.8 on 2021-11-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='added_brand',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='브랜드 id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성된 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정된 날짜')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제된 날짜')),
                ('name', models.CharField(max_length=255, verbose_name='브랜드 이름')),
                ('site_url', models.CharField(max_length=255, null=True, verbose_name='브랜드 url')),
                ('logo_url', models.CharField(max_length=255, null=True, verbose_name='로고 url')),
            ],
            options={
                'verbose_name_plural': '유저가 추가한 브랜드',
                'db_table': 'added_brands',
                'ordering': ['created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='브랜드 id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성된 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정된 날짜')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제된 날짜')),
                ('name', models.CharField(max_length=255, verbose_name='브랜드 이름')),
                ('en_name', models.CharField(max_length=255, verbose_name='브랜드 영어 이름')),
                ('site_url', models.CharField(max_length=255, null=True, verbose_name='브랜드 url')),
                ('logo_url', models.CharField(max_length=255, null=True, verbose_name='로고 url')),
                ('total_click_count', models.BigIntegerField(default=0, verbose_name='브랜드를 클릭한 횟수')),
                ('like_count', models.BigIntegerField(default=0, verbose_name='브랜드를 좋아요한 횟수')),
            ],
            options={
                'verbose_name_plural': '브랜드',
                'db_table': 'brands',
                'ordering': ['created_at'],
                'managed': True,
            },
        ),
    ]
