# Generated by Django 3.2.8 on 2021-11-04 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0004_auto_20211104_0338'),
    ]

    operations = [
        migrations.CreateModel(
            name='mainBrand',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='브랜드 id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성된 날짜')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='삭제된 날짜')),
                ('Is_deleted', models.BooleanField(default=False, verbose_name='좋아요 취소된 브랜드인지 여부')),
                ('brand_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brand.brand')),
            ],
            options={
                'verbose_name_plural': '메인에 나타낼 브랜드',
                'db_table': 'main_brands',
                'ordering': ['created_at'],
                'managed': True,
            },
        ),
    ]
