# Generated by Django 3.2.8 on 2021-11-05 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0005_mainbrand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='total_click_count',
            new_name='click_count',
        ),
    ]
