# Generated by Django 3.2.8 on 2021-10-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Product_id')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='상품 이름')),
                ('price', models.CharField(max_length=255, null=True, verbose_name='상품 가격')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='추가된 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업뎃 된 날짜')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제된 날짜')),
                ('Is_deleted', models.BooleanField(default=False, null=True, verbose_name='삭제된 상품인지 여부')),
                ('image_url', models.CharField(max_length=255, null=True, verbose_name='이미지 링크')),
                ('site_url', models.CharField(max_length=255, null=True, verbose_name='사이트 링크')),
            ],
            options={
                'verbose_name_plural': '상품',
                'db_table': 'Product',
                'ordering': ['created_at'],
                'managed': True,
            },
        ),
    ]
