# Generated by Django 3.2.8 on 2021-11-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='사용자 id')),
                ('anonymous_id', models.CharField(max_length=255, null=True, verbose_name='임시 식별 아이디')),
                ('apple_id', models.CharField(max_length=255, null=True, verbose_name='애플 아이디')),
                ('kakao_id', models.CharField(max_length=255, null=True, verbose_name='카카오 아이디')),
                ('email', models.CharField(max_length=255, null=True, verbose_name='사용자 이메일')),
                ('password', models.CharField(max_length=255, null=True, verbose_name='사용자 비밀번호')),
                ('nickname', models.CharField(max_length=255, null=True, verbose_name='사용자 별명')),
                ('profile_image', models.CharField(max_length=255, null=True, verbose_name='프로필 이미지 url')),
                ('role', models.CharField(max_length=255, null=True, verbose_name='사용자 역할')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성된 날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='수정된 날짜')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='삭제된 날짜')),
                ('Is_deleted', models.BooleanField(default=False, verbose_name='삭제된 브랜드인지 여부')),
            ],
            options={
                'verbose_name_plural': '사용자',
                'db_table': 'users',
                'ordering': ['created_at'],
                'managed': True,
            },
        ),
    ]
